package com.example.livestreamcontroller;

public enum StreamEvents {
    STREAM_RUNNING,
    STREAM_IS_SETUP,
    STREAM_TITLE,
    CHANGE_WITH_CLICKER,
    AUTO_CHANGE_TO_CAMERA,
    CURRENT_SCENE,
    CURRENT_CAMERA_SUB_SCENE,
    CURRENT_SCREEN_SUB_SCENE,
    AUGMENTED,
    TIMER_TEXT,
    TIMER_NOT_RUNNING,
    TIMER_LENGTH,
    STREAM_SOUND_ON,
    COMPUTER_SOUND_ON,
}
