package com.example.livestreamcontroller;

public enum StreamEvents {
    STREAM_RUNNING,
    STREAM_IS_SETUP,
    STREAM_TITLE,
    CHANGE_WITH_CLICKER,
    TIMER_CAN_RUN,
    CURRENT_SCENE,
    CURRENT_CAMERA_SUB_SCENE,
    CURRENT_SCREEN_SUB_SCENE,
    SCENE_IS_AUGMENTED,
    TIMER_TEXT,
    TIMER_LENGTH,
    STREAM_SOUND_ON,
    COMPUTER_SOUND_ON,
}
